name: Build SystemMonitorApp Ventura
on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest # Serveur de dernière génération (démarre instantanément)
    steps:
      - name: Récupérer le fichier ZIP
        uses: actions/checkout@v4

      - name: Décompresser le projet
        run: unzip -o SystemMonitorApp_v7.0.zip

      - name: Trouver et Compiler l'application
        run: |
          XCODEPROJ_PATH=$(find . -name "*.xcodeproj" | head -n 1)
          xcodebuild -project "$XCODEPROJ_PATH" \
                     -alltargets \
                     -configuration Release \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGN_IDENTITY="" \
                     MACOSX_DEPLOYMENT_TARGET=13.0 \
                     -derivedDataPath build

      - name: Compresser l'application finale
        run: |
          cd build/Build/Products/Release
          zip -r ../../../../SystemMonitorApp_Ventura.zip *.app

      - name: Télécharger le fichier final
        uses: actions/upload-artifact@v4
        with:
          name: SystemMonitorApp-Ventura
          path: SystemMonitorApp_Ventura.zip
